import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ReduxProvider } from "@/redux/provider";
import { NextProviders } from "./Providers/NextUI";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Welcome - Vmodel",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NextProviders>
          <ReduxProvider>{children}</ReduxProvider>
        </NextProviders>
      </body>
    </html>
  );
}
